### ISSUE TITLE
Build configuration for PRD vs Dev

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/jcountdown#105]
Currently you specify the properties file here: https://github.com/AdoptOpenJDK/jcountdown/blob/master/src/main/java/org/adoptopenjdk/jcountdown/control/PropertiesProducer.java#L12.

**Comment by atheedom** [comment]
This can be done via Maven pom. Can I take this off you? I have a solution.

**Comment by karianna** [comment]
Please do!

**Comment by atheedom** [comment]
Depending on the Maven profile selected at deployment (dev or prod) the mongo.properties will be configured for a development environment or a production environment. Configuration details are located in file src/main/resources/properties/dev or /prod.
